codes = {
100 : 'Continue',
101 : 'Switching Protocols',
102 : 'Processing',
103 : 'Early Hints',
200 : 'OK',
201 : 'Created',
202 : 'Accepted',
203 : 'Non-Authoritative Information',
204 : 'No Content',
205 : 'Reset Content',
206 : 'Partial Content',
300 : 'Multiple Choices',
301 : 'Moved Permanently',
302 : 'Found',
303 : 'See Other',
304 : 'Not Modified',
305 : 'Use Proxy',
306 : 'Unused',
307 : 'Temporary Redirect',
308 : 'Permanent Redirect',
400 : 'Bad Request',
401 : 'Unauthorized',
402 : 'Payment Required',
403 : 'Forbidden',
404 : 'Not Found',
405 : 'Method Not Allowed',
406 : 'Not Acceptable',
407 : 'Proxy Authentication Required',
408 : 'Request Timeout',
409 : 'Conflict',
410 : 'Gone',
411 : 'Length Required',
412 : 'Precondition Failed',
413 : 'Request Entity Too Large',
414 : 'Request-URI Too Long',
415 : 'Unsupported Media Type',
416 : 'Requested Range Not Satisfiable',
417 : 'Expectation Failed',
418 : 'I\'m a teapot',
421 : 'Misdirected Request',
422 : 'Unprocessable Entity',
423 : 'Locked',
425 : 'Too Early',
426 : 'Upgrade Required',
428 : 'Precondition Required',
429 : 'Too Many Requests',
431 : 'Request Header Fields Too Large',
451 : 'Unavailable For Legal Reasons',
500 : 'Internal Server Error',
501 : 'Not Implemented',
502 : 'Bad Gateway',
503 : 'Service Unavailable',
504 : 'Gateway Timeout',
505 : 'HTTP Version Not Supported',
506 : 'Variant Also Negotiates',
507 : 'Insufficient Storage',
511 : 'Network Authentication Required',
520 : 'Web server is returning an unknown error',
522 : 'Connection timed out',
524 : 'A timeout occurred'}

testedURLs = (
'https://httpstat.us/100',
'https://httpstat.us/101',
'https://httpstat.us/102',
'https://httpstat.us/103',
'https://httpstat.us/200',
'https://httpstat.us/201',
'https://httpstat.us/202',
'https://httpstat.us/203',
'https://httpstat.us/204',
'https://httpstat.us/205',
'https://httpstat.us/206',
'https://httpstat.us/300',
'https://httpstat.us/301',
'https://httpstat.us/302',
'https://httpstat.us/303',
'https://httpstat.us/304',
'https://httpstat.us/305',
'https://httpstat.us/306',
'https://httpstat.us/307',
'https://httpstat.us/308',
'https://httpstat.us/400',
'https://httpstat.us/401',
'https://httpstat.us/402',
'https://httpstat.us/403',
'https://httpstat.us/404',
'https://httpstat.us/405',
'https://httpstat.us/406',
'https://httpstat.us/407',
'https://httpstat.us/408',
'https://httpstat.us/409',
'https://httpstat.us/410',
'https://httpstat.us/411',
'https://httpstat.us/412',
'https://httpstat.us/413',
'https://httpstat.us/414',
'https://httpstat.us/415',
'https://httpstat.us/416',
'https://httpstat.us/417',
'https://httpstat.us/418',
'https://httpstat.us/421',
'https://httpstat.us/422',
'https://httpstat.us/423',
'https://httpstat.us/425',
'https://httpstat.us/426',
'https://httpstat.us/428',
'https://httpstat.us/429',
'https://httpstat.us/431',
'https://httpstat.us/451',
'https://httpstat.us/500',
'https://httpstat.us/501',
'https://httpstat.us/502',
'https://httpstat.us/503',
'https://httpstat.us/504',
'https://httpstat.us/505',
'https://httpstat.us/506',
'https://httpstat.us/507',
'https://httpstat.us/511',
'https://httpstat.us/520',
'https://httpstat.us/522',
'https://httpstat.us/524' )


msgList = [
'Continue',
'Switching Protocols',
'Processing',
'Early Hints',
'OK',
'Created',
'Accepted',
'Non-Authoritative Information',
'No Content',
'Reset Content',
'Partial Content',
'Multiple Choices',
'Moved Permanently',
'Found',
'See Other',
'Not Modified',
'Use Proxy',
'Unused',
'Temporary Redirect',
'Permanent Redirect',
'Bad Request',
'Unauthorized',
'Payment Required',
'Forbidden',
'Not Found',
'Method Not Allowed',
'Not Acceptable',
'Proxy Authentication Required',
'Request Timeout',
'Conflict',
'Gone',
'Length Required',
'Precondition Failed',
'Request Entity Too Large',
'Request-URI Too Long',
'Unsupported Media Type',
'Requested Range Not Satisfiable',
'Expectation Failed',
'I\'m a teapot',
'Misdirected Request',
'Unprocessable Entity',
'Locked',
'Too Early',
'Upgrade Required',
'Precondition Required',
'Too Many Requests',
'Request Header Fields Too Large',
'Unavailable For Legal Reasons',
'Internal Server Error',
'Not Implemented',
'Bad Gateway',
'Service Unavailable',
'Gateway Timeout',
'HTTP Version Not Supported',
'Variant Also Negotiates',
'Insufficient Storage',
'Network Authentication Required',
'Web server is returning an unknown error',
'Connection timed out',
'A timeout occurred'
]



        testUrls = [
            'https://httpstat.us/100',
            'https://httpstat.us/101',
            'https://httpstat.us/102',
            'https://httpstat.us/103',
            'https://httpstat.us/200',
            'https://httpstat.us/201',
            'https://httpstat.us/202',
            'https://httpstat.us/203',
            'https://httpstat.us/204',
            'https://httpstat.us/205',
            'https://httpstat.us/206',
            'https://httpstat.us/300',
            'https://httpstat.us/301',
            'https://httpstat.us/302',
            'https://httpstat.us/303',
            'https://httpstat.us/304',
            'https://httpstat.us/305',
            'https://httpstat.us/306',
            'https://httpstat.us/307',
            'https://httpstat.us/308',
            'https://httpstat.us/400',
            'https://httpstat.us/401',
            'https://httpstat.us/402',
            'https://httpstat.us/403',
            'https://httpstat.us/404',
            'https://httpstat.us/405',
            'https://httpstat.us/406',
            'https://httpstat.us/407',
            'https://httpstat.us/408',
            'https://httpstat.us/409',
            'https://httpstat.us/410',
            'https://httpstat.us/411',
            'https://httpstat.us/412',
            'https://httpstat.us/413',
            'https://httpstat.us/414',
            'https://httpstat.us/415',
            'https://httpstat.us/416',
            'https://httpstat.us/417',
            'https://httpstat.us/418',
            'https://httpstat.us/421',
            'https://httpstat.us/422',
            'https://httpstat.us/423',
            'https://httpstat.us/425',
            'https://httpstat.us/426',
            'https://httpstat.us/428',
            'https://httpstat.us/429',
            'https://httpstat.us/431',
            'https://httpstat.us/451',
            'https://httpstat.us/500',
            'https://httpstat.us/501',
            'https://httpstat.us/502',
            'https://httpstat.us/503',
            'htps://httpstat.us/504',
            'https://httpstat.us/505',
            'https://httpstat.us/506',
            'https://httpstat.us/507',
            'https://httpstat.us/511',
            'https://httpstat.us/520',
            'https://httpstat.us/522',
            'https://httpstat.us/524'

            ]
        messages = [
            'Continue',
            'Switching Protocols',
            'Processing',
            'Early Hints',
            'OK',
            'Created',
            'Accepted',
            'Non-Authoritative Information',
            'No Content',
            'Reset Content',
            'Partial Content',
            'Multiple Choices',
            'Moved Permanently',
            'Found',
            'See Other',
            'Not Modified',
            'Use Proxy',
            'Unused',
            'Temporary Redirect',
            'Permanent Redirect',
            'Bad Request',
            'Unauthorized',
            'Payment Required',
            'Forbidden',
            'Not Found',
            'Method Not Allowed',
            'Not Acceptable',
            'Proxy Authentication Required',
            'Request Timeout',
            'Conflict',
            'Gone',
            'Length Required',
            'Precondition Failed',
            'Request Entity Too Large',
            'Request-URI Too Long',
            'Unsupported Media Type',
            'Requested Range Not Satisfiable',
            'Expectation Failed',
            'I\'m a teapot',
            'Misdirected Request',
            'Unprocessable Entity',
            'Locked',
            'Too Early',
            'Upgrade Required',
            'Precondition Required',
            'Too Many Requests',
            'Request Header Fields Too Large',
            'Unavailable For Legal Reasons',
            'Internal Server Error',
            'Not Implemented',
            'Bad Gateway',
            'Service Unavailable',
            'Gateway Timeout',
            'HTTP Version Not Supported',
            'Variant Also Negotiates',
            'Insufficient Storage',
            'Network Authentication Required',
            'Web server is returning an unknown error',
            'Connection timed out',
            'A timeout occurred'
        ]
